name: Publish to Homebrew

on:
  # workflow_run:
  #   workflows: ["Check SemVer compliance"]
  #   types:
  #     - completed
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  homebrew-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Bump formulae
      uses: Homebrew/actions/bump-formulae@master
      with:
        # Custom GitHub access token with only the 'public_repo' scope enabled
        token: ${{secrets.HOMEBREW_ACCESS_TOKEN}}
        # Bump only these formulae if outdated
        formulae: |
          topgrade
